# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class SystemTest < Test::Unit::TestCase
  
  def test_should_raise_expected_errors_when_loading_source
    assert_equal 2,
                 $errors_count,
                 "source was expected to raise ZeroDivisionError a certain number of times"
  end
  
end

$errors_count = 0
Dir.glob(File.expand_path("#{File.dirname __FILE__}/input/**/*.rb")) do |source_file|
  begin
    require File.expand_path(source_file)
  rescue ZeroDivisionError
    $errors_count += 1
  end
end

Dir.glob(File.expand_path("#{File.dirname __FILE__}/#{ARGV.first}/**/*_test.rb")) do |test_file|
  require File.expand_path(test_file)
end
