dir_separator = Regexp.new("[#{Regexp.escape '/\\'}]+")
Dir.glob("#{File.dirname __FILE__}/system/**/*_test.rb") do |f|
  # Exclude files generated by Trapeze or that are truth output for testing
  # generation.
  next if f.split(dir_separator).any? { |d| d =~ /^output(-truth)?$/ }
  require File.expand_path(f)
end
