# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  def test_should_return_2002_02_02_when_sent_bar
    assert_equal Date.parse("2002-02-02"), bar
  end
  
  def test_should_return_2001_01_01_when_sent_foo
    assert_equal Date.parse("2001-01-01"), foo
  end
  
end
