# This file was automatically generated by Trapeze
# (http://trapeze.rubyforge.org/), the safety-net generator for Ruby.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  def test_foo_returns_nil
    assert_nil foo
  end
  
end
