# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

Dir.glob("#{File.dirname __FILE__}/../input/**/*.rb") do |source_file|
  require File.expand_path(source_file)
end

Dir.glob("#{File.dirname __FILE__}/**/*_test.rb") do |test_file|
  require File.expand_path(test_file)
end
