# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  def test_bar_returns_nil
    assert_nil bar
  end
  
  def test_foo_returns_nil
    assert_nil foo
  end
  
end
