# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class BarTest < Test::Unit::TestCase
  
  def test_is_class
    assert_instance_of Class, Bar
  end
  
end
