# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  class << self
    
    def top_level_method_calls
      @top_level_method_calls ||= {}
    end
    
  end
  
  def test_should_return_hash_when_sent_bar
    assert_equal Hash, Test_.top_level_method_calls[:bar].call
  end
  
  def test_should_return_array_when_sent_foo
    assert_equal Array, Test_.top_level_method_calls[:foo].call
  end
  
end

Test_.top_level_method_calls[:bar] = lambda { bar }
Test_.top_level_method_calls[:foo] = lambda { foo }
