# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class FooTest < Test::Unit::TestCase
  
  def setup
    @foo = Object.new
    @foo.extend Foo
  end
  
  def test_is_module
    assert_instance_of Module, Foo
  end
  
  def test_bar_returns_nil
    assert_nil @foo.bar
  end
  
  def test_baz_returns_nil
    assert_nil @foo.baz
  end
  
end
