# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class FooTest < Test::Unit::TestCase
  
  def setup
    @obj = Foo.new
  end
  
  def test_is_class
    assert_instance_of Class, Foo
  end
  
  def test_bar_returns_nil
    assert_equal nil, @obj.bar
  end
  
  def test_baz_returns_nil
    assert_equal nil, @obj.baz
  end
  
end
