# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  def test_baz_returns_bat
    assert_equal "BAT!", baz
  end
  
  def test_foo_returns_bar
    assert_equal "BAR!", foo
  end
  
end
