# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  def test_should_return_bat_when_sent_baz
    assert_equal "BAT!", baz
  end
  
  def test_should_return_bar_when_sent_foo
    assert_equal "BAR!", foo
  end
  
end
