# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class DeetTest < Test::Unit::TestCase
  
  def setup
    @deet = Deet.new
  end
  
  def test_should_be_instance_of_class
    assert_instance_of Class, Deet
  end
  
  def test_should_return_an_array_containing_con_and_can_when_sent_ban
    assert_equal [:con, :can], @deet.ban
  end
  
  def test_should_return_an_array_containing_dot_and_bin_when_sent_dit
    assert_equal [:dot, :bin], @deet.dit
  end
  
end
