# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class FooTest < Test::Unit::TestCase
  
  def setup
    @foo = Object.new
    @foo.extend Foo
  end
  
  def test_is_module
    assert_instance_of Module, Foo
  end
  
  def test_bar_returns_baz
    assert_equal :baz, @foo.bar
  end
  
  def test_bat_returns_pwop
    assert_equal :pwop, @foo.bat
  end
  
end
