# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  def test_should_return_8_88_when_sent_bar
    assert_equal 8.88, bar
  end
  
  def test_should_return_7_77_when_sent_foo
    assert_equal 7.77, foo
  end
  
end
