# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class BatTest < Test::Unit::TestCase
  
  def setup
    @bat = Bat.new
  end
  
  def test_should_be_instance_of_class
    assert_instance_of Class, Bat
  end
  
  def test_should_return_sun_apr_04_04_04_04_utc_2004_when_sent_ding
    assert_equal Time.utc(2004, 4, 4, 4, 4, 4, 4), @bat.ding
  end
  
  def test_should_return_mon_mar_03_03_03_03_utc_2003_when_sent_pwop
    assert_equal Time.utc(2003, 3, 3, 3, 3, 3, 3), @bat.pwop
  end
  
end
