# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  def test_top_level_method_bar_should_return_a_range_from_eight_to_and_excluding_88
    assert_equal 8...88, eval('bar', TOPLEVEL_BINDING)
  end
  
  def test_top_level_method_foo_should_return_a_range_from_seven_through_77
    assert_equal 7..77, eval('foo', TOPLEVEL_BINDING)
  end
  
end
