# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  def test_should_return_an_array_containing_pwop_and_ding_when_sent_bat
    assert_equal [:pwop, :ding], bat
  end
  
  def test_should_return_an_array_containing_bar_and_baz_when_sent_foo
    assert_equal [:bar, :baz], foo
  end
  
end
