# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class ArrayTest < Test::Unit::TestCase
  
  def setup
    @array = Array.new
  end
  
  def test_should_be_instance_of_class
    assert_instance_of Class, Array
  end
  
  def test_should_return_bat_when_sent_bat
    assert_equal "BAT!", @array.bat
  end
  
  def test_should_raise_runtime_error_with_message_of_this_error_also_was_raised_intentionally_when_sent_baz
    begin
      @array.baz
    rescue Exception => e
      assert_instance_of RuntimeError, e
      assert_equal "this error also was raised intentionally", e.message
    end
  end
  
end
