# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class DingTest < Test::Unit::TestCase
  
  def setup
    @ding = Object.new
    @ding.extend Ding
  end
  
  def test_is_module
    assert_instance_of Module, Ding
  end
  
  def test_dit_returns_dot
    assert_equal "DOT!", @ding.dit
  end
  
  def test_doot_returns_deet
    assert_equal "DEET!", @ding.doot
  end
  
end
