# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class ObjectTest < Test::Unit::TestCase
  
  def setup
    @object = Object.new
  end
  
  def test_should_be_instance_of_class
    assert_instance_of Class, Object
  end
  
  def test_should_return_nil_when_sent_bar
    assert_nil @object.bar
  end
  
  def test_should_return_nil_when_sent_foo
    assert_nil @object.foo
  end
  
end
