# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  def test_top_level_method_bar_should_return_bar
    assert_equal "BAR!", eval('bar', TOPLEVEL_BINDING, __FILE__, __LINE__)
  end
  
  def test_top_level_method_foo_should_raise_no_method_error_with_args_of_nil_and_message_of_this_error_was_raised_intentionally_and_name_of_nil
    begin
      eval 'foo', TOPLEVEL_BINDING, __FILE__, __LINE__
    rescue Exception => e
      assert_instance_of NoMethodError, e
      assert_nil e.args
      assert_equal "this error was raised intentionally", e.message
      assert_nil e.name
    end
  end
  
end
