# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class FooTest < Test::Unit::TestCase
  
  def setup
    @foo = Foo.new
  end
  
  def test_should_be_instance_of_class
    assert_instance_of Class, Foo
  end
  
  def test_should_return_0_666_e1_when_sent_bar
    assert_equal BigDecimal.new("0.666E1"), @foo.bar
  end
  
  def test_should_return_0_777_e1_when_sent_baz
    assert_equal BigDecimal.new("0.777E1"), @foo.baz
  end
  
end
