# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class BatTest < Test::Unit::TestCase
  
  def setup
    @bat = Bat.new
  end
  
  def test_should_be_instance_of_class
    assert_instance_of Class, Bat
  end
  
  def test_should_return_2004_04_04_t04_04_04_00_00_when_sent_ding
    assert_equal DateTime.parse("2004-04-04T04:04:04+00:00"), @bat.ding
  end
  
  def test_should_return_2003_03_03_t03_03_03_00_00_when_sent_pwop
    assert_equal DateTime.parse("2003-03-03T03:03:03+00:00"), @bat.pwop
  end
  
end
