# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class BatTest < Test::Unit::TestCase
  
  def setup
    @bat = Object.new
    @bat.extend Bat
  end
  
  def test_should_be_instance_of_module
    assert_instance_of Module, Bat
  end
  
  def test_should_return_ding_when_sent_ding
    assert_equal "DING!", @bat.ding
  end
  
  def test_should_raise_no_method_error_with_args_of_nil_and_message_of_this_error_was_raised_intentionally_and_name_of_nil_when_sent_pwop
    begin
      @bat.pwop
    rescue Exception => e
      assert_instance_of NoMethodError, e
      assert_nil e.args
      assert_equal "this error was raised intentionally", e.message
      assert_nil e.name
    end
  end
  
end
