# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  class << self
    
    def top_level_method_calls
      @top_level_method_calls ||= {}
    end
    
  end
  
  def test_should_return_a_regexp_object_when_sent_baz
    assert_equal /BAT!/, Test_.top_level_method_calls[:baz].call
  end
  
  def test_should_return_a_regexp_object_when_sent_foo
    assert_equal /BAR!/, Test_.top_level_method_calls[:foo].call
  end
  
end

Test_.top_level_method_calls[:baz] = lambda { baz }
Test_.top_level_method_calls[:foo] = lambda { foo }
