# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class ObjectTest < Test::Unit::TestCase
  
  def setup
    @object = Object.new
  end
  
  def test_should_be_instance_of_class
    assert_instance_of Class, Object
  end
  
  def test_should_return_bar_when_sent_bar
    assert_equal "BAR!", @object.bar
  end
  
  def test_should_raise_no_method_error_with_args_of_nil_and_message_of_this_error_was_raised_intentionally_and_name_of_nil_when_sent_foo
    begin
      @object.foo
    rescue Exception => e
      assert_instance_of NoMethodError, e
      assert_nil e.args
      assert_equal "this error was raised intentionally", e.message
      assert_nil e.name
    end
  end
  
end
