# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class DingTest < Test::Unit::TestCase
  
  def setup
    @ding = Ding.new
  end
  
  def test_is_class
    assert_instance_of Class, Ding
  end
  
  def test_dit_returns_dot
    assert_equal :dot, @ding.dit
  end
  
  def test_doot_returns_deet
    assert_equal :deet, @ding.doot
  end
  
end
