# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  def test_should_return_nil_when_sent_bar
    assert_nil bar
  end
  
  def test_should_return_nil_when_sent_foo
    assert_nil foo
  end
  
end
