# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class BatTest < Test::Unit::TestCase
  
  def setup
    @bat = Bat.new
  end
  
  def test_is_class
    assert_instance_of Class, Bat
  end
  
  def test_ding_returns_ding
    assert_equal "DING!", @bat.ding
  end
  
  def test_pwop_returns_pwop
    assert_equal "PWOP!", @bat.pwop
  end
  
end
