# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class FooTest < Test::Unit::TestCase
  
  def setup
    @foo = Object.new
    @foo.extend Foo
  end
  
  def test_should_be_instance_of_module
    assert_instance_of Module, Foo
  end
  
  def test_should_raise_no_method_error_with_args_of_an_empty_array_and_message_of_a_string_matching_undefined_method_this_method_also_does_not_exist_for_an_object_literal_and_name_of_this_method_also_does_not_exist_when_sent_bar
    begin
      @foo.bar
    rescue Exception => e
      assert_instance_of NoMethodError, e
      assert_equal [], e.args
      assert_match /^undefined\ method\ `this_method_also_does_not_exist'\ for\ \#<Object:0x[0-9a-f]+>$/, e.message
      assert_equal :this_method_also_does_not_exist, e.name
    end
  end
  
  def test_should_return_baz_when_sent_baz
    assert_equal "BAZ!", @foo.baz
  end
  
end
