# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

runtime_errors_count = 0
Dir.glob(File.expand_path("#{File.dirname __FILE__}/input/**/*.rb")) do |source_file|
  begin
    require File.expand_path(source_file)
  rescue RuntimeError
    runtime_errors_count += 1
  end
end
unless runtime_errors_count == 2
  raise Test::Unit::AssertionFailedError,
        "expected RuntimeError to be raised once but happened #{runtime_errors_count} time(s)"
end

unless $output_dir
  raise Test::Unit::AssertionFailedError,
        'expected $output_dir to be set to the name of the output directory'
end
Dir.glob(File.expand_path("#{File.dirname __FILE__}/#$output_dir/**/*_test.rb")) do |test_file|
  require File.expand_path(test_file)
end
