# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  class << self
    
    def top_level_method_calls
      @top_level_method_calls ||= {}
    end
    
  end
  
  def test_should_return_an_array_containing_pwop_and_ding_when_sent_bat
    assert_equal [:pwop, :ding], Test_.top_level_method_calls[:bat].call
  end
  
  def test_should_return_an_array_containing_bar_and_baz_when_sent_foo
    assert_equal [:bar, :baz], Test_.top_level_method_calls[:foo].call
  end
  
end

Test_.top_level_method_calls[:bat] = lambda { bat }
Test_.top_level_method_calls[:foo] = lambda { foo }
