# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class ArrayTest < Test::Unit::TestCase
  
  def setup
    @array = Array.new
  end
  
  def test_should_be_instance_of_class
    assert_instance_of Class, Array
  end
  
  def test_should_return_bat_when_sent_bat
    assert_equal "BAT!", @array.bat
  end
  
  def test_should_raise_zero_division_error_with_message_of_divided_by_0_when_sent_baz
    begin
      @array.baz
    rescue Exception => e
      assert_instance_of ZeroDivisionError, e
      assert_equal "divided by 0", e.message
    end
  end
  
end
