# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class ObjectTest < Test::Unit::TestCase
  
  def setup
    @object = Object.new
  end
  
  def test_should_be_instance_of_class
    assert_instance_of Class, Object
  end
  
  def test_should_return_bar_when_sent_bar
    assert_equal "BAR!", @object.bar
  end
  
  def test_should_raise_zero_division_error_with_message_of_divided_by_0_when_sent_foo
    begin
      @object.foo
    rescue Exception => e
      assert_instance_of ZeroDivisionError, e
      assert_equal "divided by 0", e.message
    end
  end
  
end
