# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  def test_should_return_hash_when_sent_bar
    assert_equal Hash, bar
  end
  
  def test_should_return_array_when_sent_foo
    assert_equal Array, foo
  end
  
end
