# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  def test_should_return_888_when_sent_bar
    assert_equal 888, bar
  end
  
  def test_should_return_777_when_sent_foo
    assert_equal 777, foo
  end
  
end
