# This file was automatically generated by Trapeze, the safety-net generator for
# Ruby. Visit http://trapeze.rubyforge.org/ for more information.

require 'test/unit'

class Test_ < Test::Unit::TestCase
  
  def test_top_level_method_bar_should_return_bar
    assert_equal "BAR!", eval('bar', TOPLEVEL_BINDING, __FILE__, __LINE__)
  end
  
  def test_top_level_method_foo_should_raise_no_method_error_with_args_of_an_empty_array_and_message_of_undefined_method_this_method_does_not_exist_for_main_object_and_name_of_this_method_does_not_exist
    begin
      eval 'foo', TOPLEVEL_BINDING, __FILE__, __LINE__
    rescue Exception => e
      assert_instance_of NoMethodError, e
      assert_equal [], e.args
      assert_equal "undefined method `this_method_does_not_exist' for main:Object", e.message
      assert_equal :this_method_does_not_exist, e.name
    end
  end
  
end
